timeout: 1200s
substitutions:
  _REGION: us-west1
  _CLUSTER: ram-dev-cluster
  _PROJECTID: resonant-cairn-369601
steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      - PROJECT_ID=$_PROJECTID
      
  - name: gcr.io/cloud-builders/kubectl
    id: create app secretes
    args: ['apply', '-f', './extras/jwt/jwt-secret.yaml', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      - PROJECT_ID=$_PROJECTID
      
  - name: gcr.io/cloud-builders/kubectl
    id: deploy bank-of-anthos
    args: ['apply', '-f', './kubernetes-manifests', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      - PROJECT_ID=$_PROJECTID
